@baseUrl = http://localhost:3000/api
@mbUrl = https://musicbrainz.org/ws/2
@deezUrl = https://api.deezer.com

POST {{baseUrl}}/albums/e4cb66b6-30b8-47d3-b0ec-07ce54727745/review
Content-Type: application/json

{
    "review": "tyler the creator the way she okokok on my computer 2"
}

###

DELETE {{baseUrl}}/albums/e4cb66b6-30b8-47d3-b0ec-07ce54727745/review

###

DELETE {{baseUrl}}/albums/e4cb66b6-30b8-47d3-b0ec-07ce54727745/rating

###
POST {{baseUrl}}/albums/e4cb66b6-30b8-47d3-b0ec-07ce54727745/rating
Content-Type: application/json

{
    "rating": 10
}

###

GET {{baseUrl}}/albums/e4cb66b6-30b8-47d3-b0ec-07ce54727745/user-data

###

DELETE {{baseUrl}}/albums/e4cb66b6-30b8-47d3-b0ec-07ce54727745/user-data

###

POST {{baseUrl}}/albums/de5a8edd-23b1-4d83-9f65-ea9fb1cd980f/review
Content-Type: application/json

{
    "review": "jschlatt is the best"
}

###
POST {{baseUrl}}/albums/de5a8edd-23b1-4d83-9f65-ea9fb1cd980f/rating
Content-Type: application/json

{
    "rating": 9
}

###
GET {{baseUrl}}/albums/library

###

GET {{baseUrl}}/profile/

###

GET {{mbUrl}}/release-group/3bd76d40-7f0e-36b7-9348-91a33afee20e?inc=releases
User-Agent: musicbox/0.7.0 ( freakybobistesting@gmail.com )
Accept: application/json

###
GET ${DEEZER_BASE}/search/album